name: "MovieRecommendationInfrastructure"
services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    secrets:
      - environment_secrets
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - movie_recomm_net

secrets:
  environment_secrets:
    file: ./.env

volumes:
  minio_data:

networks:
  movie_recomm_net:
    name: movie_recomm_net
    driver: bridge
