name: "MovieRecommendationInfrastructure"
services:
  working:
    image: python:3.11-slim
    container_name: working
    command: sleep inf
    networks:
      - movie_recomm_net
    volumes:
      - ../:/app
    working_dir: /app

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    secrets:
      - environment_secrets
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - movie_recomm_net

  spark-master:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - movie_recomm_net

  spark-worker-1:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-1
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=1800
    depends_on:
      - spark-master
    networks:
      - movie_recomm_net

  spark-worker-2:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-1
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=1800
    depends_on:
      - spark-master
    networks:
      - movie_recomm_net

secrets:
  environment_secrets:
    file: ./.env

volumes:
  minio_data:

networks:
  movie_recomm_net:
    name: movie_recomm_net
    driver: bridge
