name: "MovieRecommendationInfrastructure"
services:
  working:
    image: python:3.11-slim
    container_name: working
    command: sleep inf
    networks:
      - movie_recomm_net
    volumes:
      - ../:/app
    working_dir: /app

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    secrets:
      - environment_secrets
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - movie_recomm_net

  spark-master:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-master
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOG_DIR=/host/spark_master_logs
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark_master_logs:/host/spark_master_logs
    networks:
      - movie_recomm_net

  spark-worker-1:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-1
    user: root
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOCAL_DIRS=/host/spark_worker1_tmp
      - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=1800 -Dspark.worker.cleanup.appDataTtl=3600
    depends_on:
      - spark-master
    volumes:
      - spark_worker1_tmp:/host/spark_worker1_tmp
    networks:
      - movie_recomm_net

  spark-worker-2:
    image: apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu
    container_name: spark-worker-2
    user: root
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=2
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOCAL_DIRS=/host/spark_worker2_tmp
      - SPARK_WORKER_OPTS=-Dspark.worker.cleanup.enabled=true -Dspark.worker.cleanup.interval=1800 -Dspark.worker.cleanup.appDataTtl=3600
    depends_on:
      - spark-master
    volumes:
      - spark_worker2_tmp:/host/spark_worker2_tmp
    networks:
      - movie_recomm_net

secrets:
  environment_secrets:
    file: ./.env

volumes:
  minio_data:
  spark_master_logs:
  spark_worker1_tmp:
  spark_worker2_tmp:

networks:
  movie_recomm_net:
    name: movie_recomm_net
    driver: bridge
